version: "3.7"
services:
  database:
    image: mongo
    volumes: 
      - pa11y-mongo-volume:/pa11ydata
    restart: always
    ports:
      - "27017:27017"
    expose:
      - "27017"
  web:
    depends_on:
      - database
    image: pallespm/pa11y-docker
    # build: .
    ports:
      - "80:4000"
      - "3000:3000"
    restart: always
volumes:
  pa11y-mongo-volume:
