apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pa11y-mongo-volume
  name: pa11y-mongo-volume
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
